# Generated by Django 4.2.7 on 2023-11-20 17:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('Alm', models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^ALM-[0-9]{3}$', 'Formato de Alm no válido')])),
                ('NombreA', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=40, unique=True)),
                ('Provincia', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('CodigoA', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('TipoA', models.CharField(max_length=20)),
                ('DescripcionA', models.CharField(max_length=100)),
                ('LocalizacionA', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('DNIE', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('NombreE', models.CharField(max_length=20)),
                ('Apellido1E', models.CharField(max_length=20)),
                ('Apellido2E', models.CharField(max_length=20)),
                ('TelefonoE', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('Num_factura', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Receptor', models.CharField(max_length=20)),
                ('TipoG', models.CharField(max_length=20)),
                ('CantG', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('Ref_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Emisor', models.CharField(max_length=20)),
                ('TipoI', models.CharField(max_length=20)),
                ('CantI', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Prod', models.BigIntegerField(primary_key=True, serialize=False)),
                ('NombreP', models.CharField(max_length=20)),
                ('DescripcionP', models.CharField(max_length=320)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('DNIS', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('NombreS', models.CharField(max_length=20)),
                ('Apellido1S', models.CharField(max_length=20)),
                ('Apellido2S', models.CharField(max_length=20)),
                ('TelefonoS', models.IntegerField(unique=True)),
                ('E_mailS', models.EmailField(max_length=320, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nomina_tiene',
            fields=[
                ('Nomina', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Bruto', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Impuesto', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('DNIE', models.CharField(max_length=9, null=True)),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Genera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_factura', models.IntegerField(unique=True)),
                ('Fecha', models.DateField()),
                ('Nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nomina_tiene')),
            ],
            options={
                'unique_together': {('Nomina', 'Num_factura', 'Fecha')},
            },
        ),
    ]
