# Generated by Django 4.2.7 on 2023-11-25 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genera',
            name='id',
        ),
        migrations.AlterField(
            model_name='genera',
            name='Nomina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.nomina_tiene'),
        ),
        migrations.CreateModel(
            name='Conlleva',
            fields=[
                ('Num_factura', models.IntegerField(unique=True)),
                ('Producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.producto')),
                ('Fecha', models.DateField()),
            ],
            options={
                'unique_together': {('Num_factura', 'Producto', 'Fecha')},
            },
        ),
    ]
