# Generated by Django 4.2.7 on 2024-01-11 11:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genera',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='genera',
            name='Nomina',
        ),
        migrations.RemoveField(
            model_name='genera',
            name='Num_factura',
        ),
        migrations.AddField(
            model_name='gaston',
            name='FechaN',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gaston',
            name='Nomina_tiene',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='app.nomina_tiene'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastop',
            name='CantidadC',
            field=models.PositiveIntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastop',
            name='FechaN',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gaston',
            name='CantG',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=0.01, message='El campo debe ser un número mayor que 0')]),
        ),
        migrations.AlterField(
            model_name='gastop',
            name='CantG',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=0.01, message='El campo debe ser un número mayor que 0')]),
        ),
        migrations.AlterField(
            model_name='nomina_tiene',
            name='Bruto',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=0.01, message='El campo debe ser un número mayor que 0')]),
        ),
        migrations.DeleteModel(
            name='conlleva',
        ),
        migrations.DeleteModel(
            name='genera',
        ),
    ]
